-- 1) عمود request_no معرّف كـ GENERATED ALWAYS، وده بيمنع أي تحديث مباشر عليه.
--    نحوّله إلى GENERATED BY DEFAULT: نفس السلوك التلقائي للطلبات الجديدة،
--    لكن بيسمح بالتعديل اليدوي وقت الحاجة (زي إعادة الترقيم دي).
alter table public.requests alter column request_no set generated by default;

-- 2) إعادة ترقيم الطلبات الموجودة حاليًا من 1، بنفس ترتيبها الحالي
with ordered as (
  select id, row_number() over (order by request_no) as new_no
  from public.requests
)
update public.requests r
set request_no = ordered.new_no
from ordered
where r.id = ordered.id;

-- 3) ضبط العداد عشان أي طلب جديد يكمل صح من بعد آخر رقم مستخدم
select setval(
  pg_get_serial_sequence('public.requests', 'request_no'),
  (select coalesce(max(request_no), 0) from public.requests)
);
