-- =====================================================================
--  06 — أساس شاشة الأدمن: تعطيل المستخدمين + تحكّم الأدمن + بداية التسلسل
--  ينفّذ بعد 02 (admin role + current_role_of).
-- =====================================================================

-- 1) تعطيل/تفعيل المستخدم
alter table public.profiles add column if not exists is_active boolean not null default true;

-- 2) السماح للأدمن بتعديل المستخدمين (الدور/التفعيل/الاسم).
--    الكتابة من العميل كانت مقفولة تمامًا؛ ده يفتح مسارًا للأدمن فقط لشاشة الإدارة.
--    (الإدراج ما زال عبر trigger/service_role فقط — لا self-signup.)
drop policy if exists profiles_admin_write on public.profiles;
create policy profiles_admin_write on public.profiles for update
  using (current_role_of() = 'admin') with check (current_role_of() = 'admin');

-- 3) التحكّم في بداية التسلسل (لمواصلة تسلسل الإدارة المالية القديم).
--    نحوّل العمود من GENERATED ALWAYS إلى BY DEFAULT كي يسري setval.
alter table public.requests alter column request_no set generated by default;

create or replace function public.admin_set_request_start(p_next bigint)
returns bigint
language plpgsql security definer set search_path = public
as $$
declare mx bigint;
begin
  if current_role_of() <> 'admin' then
    raise exception 'هذه العملية للأدمن فقط';
  end if;
  select coalesce(max(request_no), 0) into mx from public.requests;
  if p_next <= mx then
    raise exception 'الرقم يجب أن يكون أكبر من آخر رقم حالي (%)', mx;
  end if;
  perform setval(pg_get_serial_sequence('public.requests','request_no'), p_next - 1, true);
  return p_next;
end;
$$;
revoke execute on function public.admin_set_request_start(bigint) from anon;
